// MEVN-App/frontend/src/pages/Login.vue
<template>
  <div class="p-8 max-w-md mx-auto">
    <h2 class="text-2xl font-bold mb-4">Login</h2>
    <form @submit.prevent="login">
      <input v-model="email" type="email" placeholder="Email" class="border p-2 w-full mb-3" />
      <input v-model="password" type="password" placeholder="Password" class="border p-2 w-full mb-3" />
      <button type="submit" class="bg-green-500 text-white px-4 py-2">Login</button>
    </form>
    <p class="text-red-500 mt-3">{{ error }}</p>
  </div>
</template>

<script>
import API from "../services/api";

export default {
  data() {
    return {
      email: "",
      password: "",
      error: "",
    };
  },
  methods: {
    async login() {
      try {
        const res = await API.post("/auth/login", {
          email: this.email,
          password: this.password,
        });
        localStorage.setItem("token", res.data.token);
        if (res.data.user.role === "member") {
          this.$router.push("/donor");
        } else {
          this.$router.push("/beneficiary");
        }
      } catch (err) {
        this.error = err.response?.data?.msg || "Login failed";
      }
    },
  },
};
</script>

// MEAN-App/frontend/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { ApiService } from '../../services/api.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html'
})
export class LoginComponent {
  form = { email: '', password: '' };
  msg = '';

  constructor(private api: ApiService, private router: Router) {}

  login() {
    this.api.login(this.form).subscribe({
      next: (res) => {
        // ✅ Save token and user
        localStorage.setItem('token', res.token);
        localStorage.setItem('user', JSON.stringify(res.user));
        this.msg = 'Login successful!';

        // ✅ Navigate by role
        if (res.user.role === 'member') {
          this.router.navigate(['/donor-dashboard']);
        } else {
          this.router.navigate(['/beneficiary-dashboard']);
        }
      },
      error: (err) => {
        this.msg = err.error?.msg || 'Invalid credentials';
      }
    });
  }
}

<div class="container mt-5">
  <div class="card p-4 shadow">
    <h2 class="text-center mb-4">Login</h2>

    <input
      [(ngModel)]="form.email"
      type="email"
      placeholder="Email"
      class="form-control mb-3"
    />

    <input
      [(ngModel)]="form.password"
      type="password"
      placeholder="Password"
      class="form-control mb-3"
    />

    <button (click)="login()" class="btn btn-success w-100">Login</button>

    <p class="text-danger mt-3 text-center">{{ msg }}</p>
  </div>
</div>
