// MEAN-App/frontend/src/app/components/donor-dashboard/donor-dashboard.component.ts
import { Component } from '@angular/core';
import { ApiService } from 'src/app/services/api.service';

@Component({
  selector: 'app-donor-dashboard',
  templateUrl: './donor-dashboard.component.html',
})
export class DonorDashboardComponent {
  product = {
    productName: '',
    companyName: '',
    quantity: 0,
    tokenCost: 0,
    waitTime: 0,
    donorId: '' // later to be replaced with actual donor _id (e.g. from login)
  };

  constructor(private api: ApiService) {}

  addProduct() {
    // Optional: replace 'donorId' if you have it in storage
    this.api.addProduct(this.product).subscribe({
      next: (res) => {
        alert('Product added successfully!');
        this.product = {
          productName: '',
          companyName: '',
          quantity: 0,
          tokenCost: 0,
          waitTime: 0,
          donorId: ''
        };
      },
      error: (err) => {
        console.error(err);
        alert('Failed to add product.');
      }
    });
  }
}

<div class="form-container">
  <h2>Add New Meal</h2>

  <form (ngSubmit)="addProduct()">
    <input [(ngModel)]="product.productName" name="productName" placeholder="Product Name" required />
    <input [(ngModel)]="product.companyName" name="companyName" placeholder="Company" required />
    <input [(ngModel)]="product.quantity" name="quantity" type="number" placeholder="Quantity" required />
    <input [(ngModel)]="product.tokenCost" name="tokenCost" type="number" placeholder="Token Cost" required />
    <input [(ngModel)]="product.waitTime" name="waitTime" type="number" placeholder="Wait Time (mins)" required />

    <button type="submit">Add Product</button>
  </form>
</div>

// MEVN-App/frontend/src/pages/DonorDashboard.vue
<template>
  <div class="form-container">
    <h2>Add Product</h2>
    <form @submit.prevent="addProduct">
      <input v-model="product.productName" placeholder="Product Name" />
      <input v-model="product.companyName" placeholder="Company" />
      <input v-model="product.quantity" type="number" placeholder="Quantity" />
      <input v-model="product.tokenCost" type="number" placeholder="Token Cost" />
      <input v-model="product.waitTime" type="number" placeholder="Wait Time (mins)" />
      <button type="submit">Add</button>
    </form>
  </div>
</template>

<script>
import axios from 'axios';
export default {
  data() {
    return {
      product: {
        productName: '',
        companyName: '',
        quantity: 0,
        tokenCost: 0,
        waitTime: 0,
        donorId: '' // should get from login session ideally
      }
    };
  },
  methods: {
    async addProduct() {
      await axios.post('/api/products', this.product);
      alert("Product added!");
    }
  }
};
</script>
