// MEAN-App/frontend/src/app/components/register/register.component.ts
import { Component } from '@angular/core';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html'
})
export class RegisterComponent {
  form = { name: '', email: '', password: '', role: 'beneficiary' };
  msg = '';

  constructor(private api: ApiService) {}

  register() {
    this.api.register(this.form).subscribe({
      next: (res) => {
        localStorage.setItem('token', res.token);
        this.msg = 'Registered successfully!';
      },
      error: (err) => {
        this.msg = err.error?.msg || 'Error';
      }
    });
  }
}

<div class="container mt-5">
  <h2>Register</h2>
  <input [(ngModel)]="form.name" placeholder="Name" class="form-control mb-2" />
  <input [(ngModel)]="form.email" placeholder="Email" class="form-control mb-2" />
  <input [(ngModel)]="form.password" type="password" placeholder="Password" class="form-control mb-2" />
  <select [(ngModel)]="form.role" class="form-control mb-2">
    <option value="beneficiary">Beneficiary</option>
    <option value="member">Member</option>
  </select>
  <button (click)="register()" class="btn btn-primary">Register</button>
  <p class="text-danger mt-2">{{ msg }}</p>
</div>

// MEVN-App/frontend/src/pages/Register.vue
<template>
  <div class="p-8 max-w-md mx-auto">
    <h2 class="text-2xl font-bold mb-4">Register</h2>
    <form @submit.prevent="register">
      <input v-model="name" placeholder="Name" class="border p-2 w-full mb-3" />
      <input v-model="email" type="email" placeholder="Email" class="border p-2 w-full mb-3" />
      <input v-model="password" type="password" placeholder="Password" class="border p-2 w-full mb-3" />
      <select v-model="role" class="border p-2 w-full mb-3">
        <option value="member">Member</option>
        <option value="beneficiary">Beneficiary</option>
      </select>
      <button type="submit" class="bg-blue-500 text-white px-4 py-2">Register</button>
    </form>
    <p class="text-red-500 mt-3">{{ error }}</p>
  </div>
</template>

<script>
import API from "../services/api";

export default {
  data() {
    return {
      name: "",
      email: "",
      password: "",
      role: "beneficiary",
      error: "",
    };
  },
  methods: {
    async register() {
      try {
        const res = await API.post("/auth/register", {
          name: this.name,
          email: this.email,
          password: this.password,
          role: this.role,
        });
        localStorage.setItem("token", res.data.token);
        if (this.role === "member") {
          this.$router.push("/donor");
        } else {
          this.$router.push("/beneficiary");
        }
      } catch (err) {
        this.error = err.response?.data?.msg || "Error registering";
      }
    },
  },
};
</script>
